# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dec0296cdef0eda5fdd807dfd746f2b122cf8729ced37b7873cac418c1e04fba0e090977eb814ff6b92f43169bc363d55bfa9dfdd3ed6b51755d254f9e64b13b

test:
  secret_key_base: b2814a19779d0e8b39791f307a76574cf35efad7e3094fcfdd7632aabbf09f1b49f956db0ad4982ca4139b8f0b0b5fc289e8cf50c192bbcc081cec9131181d1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
